name: bla-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.79
  - ipython=8.1.1
  - jupyter=1.0.0
  - mafft=7.490
  - mash=2.3
  - matplotlib=3.5.2
  - minimap2=2.24
  - numpy=1.22.3
  - pandas=1.4.1
  - pip=22.0.4
  - python=3.9.12
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - seaborn=0.11.2
  - pip:
      - git+https://github.com/mmolari/pypangraph@0.1.0
